# Generated by Django 3.2.4 on 2021-06-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='text',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
