# Generated by Django 3.2.4 on 2021-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_materials',
            field=models.FileField(null=True, upload_to='lesson_materials', verbose_name='Материалы по уроку'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_video_material',
            field=models.FileField(null=True, upload_to='lesson_video_material', verbose_name='Видео материалы'),
        ),
    ]
