# Generated by Django 3.2.4 on 2021-06-23 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_auto_20210623_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название домашнего задания')),
                ('description', models.TextField(verbose_name='Описание домашнего задания')),
                ('homework_materials', models.FileField(null=True, upload_to='homework_materials', verbose_name='Материалы по домашнему заданию')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_homework', to='courses.lesson')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsHomeworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homework', to='courses.homework')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homework_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
